import type { CSSProperties } from 'react'
import {
  IconActivityHeartbeat,
  IconAdjustments,
  IconAlertCircle,
  IconAlertTriangle,
  IconArmchair,
  IconArrowDownLeft,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpRight,
  IconBell,
  IconBellCog,
  IconBolt,
  IconBrandFacebook,
  IconBrandGoogle,
  IconBuilding,
  IconBuildingArch,
  IconBuildingBank,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCalendar,
  IconCalendarEvent,
  IconCameraHeart,
  IconCameraPlus,
  IconCash,
  IconChartBar,
  IconCheck,
  IconCheckbox,
  IconChecks,
  IconChevronDown,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconClipboardCheck,
  IconClipboardList,
  IconClock,
  IconCloud,
  IconCloudCheck,
  IconCloudDownload,
  IconCloudOff,
  IconCloudUpload,
  IconCoin,
  IconCoins,
  IconCompass,
  IconCreditCard,
  IconCurrentLocation,
  IconDatabasePlus,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDeviceWatch,
  IconDiamond,
  IconDiscount,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconFileExport,
  IconFlag2,
  IconFlask,
  IconGift,
  IconGiftCard,
  IconHeart,
  IconHeartFilled,
  IconHeartRateMonitor,
  IconHelpCircle,
  IconHistory,
  IconHome,
  IconId,
  IconIdBadge2,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayoutDashboard,
  IconList,
  IconListCheck,
  IconLoader2,
  IconListSearch,
  IconLock,
  IconLockCheck,
  IconLogin,
  IconLogout,
  IconMail,
  IconMap2,
  IconMapCog,
  IconMapOff,
  IconMapPin,
  IconMapPinCheck,
  IconMapPinHeart,
  IconMapPinPlus,
  IconMapSearch,
  IconMenu2,
  IconMessage,
  IconMessage2,
  IconMessageCircle,
  IconMessageDots,
  IconMessages,
  IconMinus,
  IconPackage,
  IconPencil,
  IconPhone,
  IconPhoneCall,
  IconPhoto,
  IconPhotoOff,
  IconPhotoPlus,
  IconPhotoUp,
  IconPlane,
  IconPlaneArrival,
  IconPlaneDeparture,
  IconPlaneInflight,
  IconPlaneOff,
  IconPlaneTilt,
  IconPlayerPlay,
  IconPlus,
  IconPoint,
  IconQrcode,
  IconRadar,
  IconReceipt,
  IconReceipt2,
  IconReceiptOff,
  IconRefresh,
  IconReportMoney,
  IconScale,
  IconSearch,
  IconSearchOff,
  IconSend,
  IconSettings,
  IconShare,
  IconShieldCheck,
  IconShieldLock,
  IconShoppingBag,
  IconShoppingCart,
  IconShoppingCartOff,
  IconShoppingCartPlus,
  IconSparkles,
  IconSpeakerphone,
  IconSquare,
  IconStar,
  IconStarFilled,
  IconStarHalf,
  IconTarget,
  IconTemperature,
  IconTicket,
  IconTrash,
  IconTree,
  IconTrendingUp,
  IconTruck,
  IconTruckDelivery,
  IconUpload,
  IconUrgent,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserOff,
  IconUserPlus,
  IconUserStar,
  IconUsers,
  IconUsersGroup,
  IconWallet,
  IconWorldLatitude,
  IconWritingSign,
  IconX,
} from '@tabler/icons-react'

/* 使用中的圖示（僅這些會被打包）；新增圖示時在此登記 */
const ICONS = {
  'activity-heartbeat': IconActivityHeartbeat,
  'adjustments': IconAdjustments,
  'alert-circle': IconAlertCircle,
  'alert-triangle': IconAlertTriangle,
  'armchair': IconArmchair,
  'arrow-down-left': IconArrowDownLeft,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-up-right': IconArrowUpRight,
  'bell': IconBell,
  'bell-cog': IconBellCog,
  'bolt': IconBolt,
  'brand-facebook': IconBrandFacebook,
  'brand-google': IconBrandGoogle,
  'building': IconBuilding,
  'building-arch': IconBuildingArch,
  'building-bank': IconBuildingBank,
  'building-store': IconBuildingStore,
  'building-warehouse': IconBuildingWarehouse,
  'calendar': IconCalendar,
  'calendar-event': IconCalendarEvent,
  'camera-heart': IconCameraHeart,
  'camera-plus': IconCameraPlus,
  'cash': IconCash,
  'chart-bar': IconChartBar,
  'check': IconCheck,
  'checkbox': IconCheckbox,
  'checks': IconChecks,
  'chevron-down': IconChevronDown,
  'chevron-right': IconChevronRight,
  'chevron-up': IconChevronUp,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  'clipboard-check': IconClipboardCheck,
  'clipboard-list': IconClipboardList,
  'clock': IconClock,
  'cloud': IconCloud,
  'cloud-check': IconCloudCheck,
  'cloud-download': IconCloudDownload,
  'cloud-off': IconCloudOff,
  'cloud-upload': IconCloudUpload,
  'coin': IconCoin,
  'coins': IconCoins,
  'compass': IconCompass,
  'credit-card': IconCreditCard,
  'current-location': IconCurrentLocation,
  'database-plus': IconDatabasePlus,
  'device-floppy': IconDeviceFloppy,
  'device-mobile': IconDeviceMobile,
  'device-watch': IconDeviceWatch,
  'diamond': IconDiamond,
  'discount': IconDiscount,
  'download': IconDownload,
  'edit': IconEdit,
  'external-link': IconExternalLink,
  'file-export': IconFileExport,
  'flag-2': IconFlag2,
  'flask': IconFlask,
  'gift': IconGift,
  'gift-card': IconGiftCard,
  'heart': IconHeart,
  'heart-filled': IconHeartFilled,
  'heart-rate-monitor': IconHeartRateMonitor,
  'help-circle': IconHelpCircle,
  'history': IconHistory,
  'home': IconHome,
  'id': IconId,
  'id-badge-2': IconIdBadge2,
  'inbox': IconInbox,
  'info-circle': IconInfoCircle,
  'key': IconKey,
  'layout-dashboard': IconLayoutDashboard,
  'list': IconList,
  'list-check': IconListCheck,
  'list-search': IconListSearch,
  'loader-2': IconLoader2,
  'lock': IconLock,
  'lock-check': IconLockCheck,
  'login': IconLogin,
  'logout': IconLogout,
  'mail': IconMail,
  'map-2': IconMap2,
  'map-cog': IconMapCog,
  'map-off': IconMapOff,
  'map-pin': IconMapPin,
  'map-pin-check': IconMapPinCheck,
  'map-pin-heart': IconMapPinHeart,
  'map-pin-plus': IconMapPinPlus,
  'map-search': IconMapSearch,
  'menu-2': IconMenu2,
  'message': IconMessage,
  'message-2': IconMessage2,
  'message-circle': IconMessageCircle,
  'message-dots': IconMessageDots,
  'messages': IconMessages,
  'minus': IconMinus,
  'package': IconPackage,
  'pencil': IconPencil,
  'phone': IconPhone,
  'phone-call': IconPhoneCall,
  'photo': IconPhoto,
  'photo-off': IconPhotoOff,
  'photo-plus': IconPhotoPlus,
  'photo-up': IconPhotoUp,
  'plane': IconPlane,
  'plane-arrival': IconPlaneArrival,
  'plane-departure': IconPlaneDeparture,
  'plane-inflight': IconPlaneInflight,
  'plane-off': IconPlaneOff,
  'plane-tilt': IconPlaneTilt,
  'player-play': IconPlayerPlay,
  'plus': IconPlus,
  'point': IconPoint,
  'qrcode': IconQrcode,
  'radar': IconRadar,
  'receipt': IconReceipt,
  'receipt-2': IconReceipt2,
  'receipt-off': IconReceiptOff,
  'refresh': IconRefresh,
  'report-money': IconReportMoney,
  'scale': IconScale,
  'search': IconSearch,
  'search-off': IconSearchOff,
  'send': IconSend,
  'settings': IconSettings,
  'share': IconShare,
  'shield-check': IconShieldCheck,
  'shield-lock': IconShieldLock,
  'shopping-bag': IconShoppingBag,
  'shopping-cart': IconShoppingCart,
  'shopping-cart-off': IconShoppingCartOff,
  'shopping-cart-plus': IconShoppingCartPlus,
  'sparkles': IconSparkles,
  'speakerphone': IconSpeakerphone,
  'square': IconSquare,
  'star': IconStar,
  'star-filled': IconStarFilled,
  'star-half': IconStarHalf,
  'target': IconTarget,
  'temperature': IconTemperature,
  'ticket': IconTicket,
  'trash': IconTrash,
  'tree': IconTree,
  'trending-up': IconTrendingUp,
  'truck': IconTruck,
  'truck-delivery': IconTruckDelivery,
  'upload': IconUpload,
  'urgent': IconUrgent,
  'user': IconUser,
  'user-check': IconUserCheck,
  'user-circle': IconUserCircle,
  'user-off': IconUserOff,
  'user-plus': IconUserPlus,
  'user-star': IconUserStar,
  'users': IconUsers,
  'users-group': IconUsersGroup,
  'wallet': IconWallet,
  'world-latitude': IconWorldLatitude,
  'writing-sign': IconWritingSign,
  'x': IconX,
}

export type IconName = keyof typeof ICONS

/* 以 <i> 包住 SVG，沿用既有 CSS 的 font-size / color 設定 */
export function Icon({ name, className, style }: { name: IconName; className?: string; style?: CSSProperties }) {
  const Svg = ICONS[name]
  return (
    <i className={className ? `ti ${className}` : 'ti'} style={style} aria-hidden="true">
      <Svg size="1em" stroke={2} />
    </i>
  )
}
